### ISSUE TITLE
XSS issue

### ISSUE THREAD

**Issue by balcsida** [Awilum/monstra-cms#344]
Like:
/monstra/?"onmouseover='prompt(980991)'bad=">
/monstra/blog/hello-world"><script>prompt(911267)</script>

**Comment by fadlisaad** [comment]
```
http://monstra-site/admin/"><script>alert(2188772)</script>'
```

Sometime it will show popup, sometime is not. I'm using IBM Rational AppScan

**Comment by razuro** [comment]
Tested this on https://demos3.softaculous.com/Monstra/admin
Just got 404

**Comment by fadlisaad** [comment]
You need to use IE with XSS filter off

—<br>Sent from <a href="https://www.dropbox.com/mailbox">Mailbox</a>

On Thursday Jan 15, 2015 at 10:45, razuro <notifications@github.com>, wrote:

Tested this on https://demos3.softaculous.com/Monstra/admin
Just got 404

---

**Comment by gramimoss** [comment]
Confirmed XSS is still a problem on monstra 3.0.1 

Used IE:10 with XSS filter: off 
```
http://www.domain.com/?"/><script>alert(980991);</script>"
```
PHP command that causes XSS:
```
<meta property="og:url" content="<?php echo Url::current(); ?>">
```
Result:
```
<meta property="og:url" content="http://www.domain.com/?"/><script>alert(980991);</script>"">
```

Problem with Gelato Lib:
```
    public static function current()
    {
        return (!empty($_SERVER['HTTPS'])) ? "https://".$_SERVER['SERVER_NAME'].$_SERVER['REQUEST_URI'] : "http://".$_SERVER['SERVER_NAME'].$_SERVER['REQUEST_URI'];
    }
```
Solution:
```
    public static function current()
    {
        return (!empty($_SERVER['HTTPS'])) ? Security::sanitizeURL("https://".$_SERVER['SERVER_NAME'].$_SERVER['REQUEST_URI']) : Security::sanitizeURL("http://".$_SERVER['SERVER_NAME'].$_SERVER['REQUEST_$
    }

```
