### ISSUE TITLE
Minify failed for new theme

### ISSUE THREAD

**Issue by razuro** [Awilum/monstra-cms#355]
How to reproduce:
1. copy existing default theme folder, then rename it to e.g: defaultx
2. edit default.css anything, change color, etc in Admin Panel -> Extend -> Themes -> Styles -> Edit button
3. delete temporary files in Admin Panel -> System -> Settings -> Delete Temporary Files
4. Visit your frontend, refresh, view minified css, no changes done

**Comment by razuro** [comment]
As a workaround, rename the default as something else, then rename your new theme as default. It should work.

**Comment by thoncs** [comment]
For the new theme to show changes you'll need to correct the paths in header.php to match the name of the new theme. Otherwise, even if you have enabled the new theme it will still pull styles from the theme named 'default'.
```
 <?php Stylesheet::add('public/themes/default/css/default.css', 'frontend', 2); ?>
 ```
```
 <?php Stylesheet::add('public/themes/defaultx/css/defaultx.css', 'frontend', 2); ?>
```

**Comment by razuro** [comment]
Good catch. Haven't used Monstra in a while, I might have overlooked this. 

Thank you @thoncs.
